# Generated by Django 4.2.15 on 2025-06-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineuser',
            name='name',
        ),
        migrations.AddField(
            model_name='lineuser',
            name='access_token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='lineuser',
            name='access_token_expire_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lineuser',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='lineuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
